const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),Features=require('../code/lens_features.js'),Visual=require('../code/lens_visual.js'),Protocol=require('../code/lens_protocol.js');
let count=0;function test(name,fn){fn();console.log('✓ '+name);count++;}
const silence=Array(12).fill(0);
function raw7(a){return [a[0]*.3,a[0],a[0]*.4,a[1]*.35,a[1],a[1]*.3,a[2],a[2]*.4,a[3],a[4],a[5],a[6]];}
test('Silence never invents beats or winds reference gain into noise',()=>{let e=new Features.Engine();for(let i=1;i<1500;i++)e.step(silence,i*.02,1);assert.equal(e.count,0);assert.equal(e.tempo,0);assert.equal(e.pulse,0);assert.equal(e.energy,0);assert(e.ref>=.018);});
test('Non-finite / extreme feature inputs cannot poison state',()=>{let e=new Features.Engine();for(let i=1;i<100;i++)e.step(raw7([NaN,Infinity,-1,NaN,0,0,Infinity]),i*.02,1);for(const k of ['energy','confidence','db','crest','width'])assert(Number.isFinite(e.snapshot()[k]));});
test('Sustained energy is not a stream of onsets',()=>{let e=new Features.Engine();for(let i=1;i<400;i++)e.step(raw7([.08,.03,.01,.1,.15,.1,0]),i*.02,1);assert(e.count<2);assert.equal(e.pulse,0);});
test('120 BPM transients establish a pulse; silence releases it',()=>{let e=new Features.Engine();for(let i=1;i<900;i++){let phase=(i*.02)%.5,a=.22*Math.exp(-phase/0.04);e.step(raw7([a,a*.2,a*.4,a,.3, a,0]),i*.02,1);}assert(Math.abs(e.tempo-120)<4,JSON.stringify(e.snapshot()));assert(e.confidence>.48);for(let i=900;i<1150;i++)e.step(silence,i*.02,1);assert(e.confidence<.08);assert.equal(e.tempo,0);});
test('Input level adapts across recordings without title-specific settings',()=>{function run(level){let e=new Features.Engine();for(let i=1;i<2000;i++){let a=level*(.7+.3*Math.sin(i*.04));e.step(raw7([a*.4,a*.7,a*.2,a,a*1.5,a,0]),i*.02,1);}return e.energy;}assert(Math.abs(run(.06)-run(.25))<.12);});
test('Stop/reset discards previous track tempo and onset history',()=>{let e=new Features.Engine();for(let i=1;i<300;i++)e.step(raw7([.1,0,0,.1,.2,.1,0]),i*.02,1);e.reset();assert.equal(e.count,0);assert.equal(e.hist.length,0);assert.equal(e.tempo,0);});
const params={scene:0,freeze:false,black:false,brightness:.6,trails:.25,detail:.55,bassWeight:1.2,focus:0};
function f(){return {bands:[.5,.35,.18],energy:.6,slow:.4,brightness:.35,width:.2,pulse:0,count:0,active:true,body:.5,midContour:.5,counts:[0,0,0],transients:[0,0,0]};}
test('All scenes share bounded RGB and a restrained full-frame light budget',()=>{for(let scene=0;scene<=5;scene++){let v=new Visual.Engine();for(let t=0;t<160;t++){let a=v.step({...f(),count:t,counts:[t,t,t],transients:[.6,.4,.8]},.05,{...params,scene});assert.equal(a.length,192);assert(a.every(n=>Number.isInteger(n)&&n>=0&&n<=127));let sum=0;for(let i=0;i<64;i++)sum+=Math.max(...a.slice(i*3,i*3+3))/127;assert(sum<9);assert(v.particles.length<=32);}}});
test('Touch causes a local response even during silence and frozen background',()=>{let v=new Visual.Engine(),z={...f(),bands:[0,0,0],body:0,energy:0,slow:0,count:0,active:false};let before=v.step(z,.05,{...params,freeze:true});v.touch(11,110);let after=v.step(z,.05,{...params,freeze:true});assert(Math.max(...after.slice(0,3))>Math.max(...before.slice(0,3))+20);});
test('Pressure changes gesture strength; release and clear cannot leave stuck touches',()=>{let v=new Visual.Engine();v.touch(44,50);v.pressure(44,10);let a=v.gesture().strength;v.pressure(44,120);assert(v.gesture().strength>a);v.touch(55,80);v.release(44);assert.equal(v.gesture().count,1);v.clear();assert.equal(v.gesture().count,0);});
test('Every 8x8 pad is spatial, with stable bottom-left MIDI mapping',()=>{let v=new Visual.Engine();for(let y=0;y<8;y++)for(let x=0;x<8;x++){let n=Protocol.pad(x,y);assert.deepEqual(Protocol.xy(n),[x,y]);assert(v.touch(n,80));assert.deepEqual([v.held[n].x,v.held[n].y],[x,y]);}assert.equal(v.gesture().count,64);assert(!v.touch(91,80));});
test('Blackout overrides audio, touch and frozen trails',()=>{let v=new Visual.Engine();v.touch(55,127);let a=v.step(f(),.05,{...params,black:true,freeze:true});assert(a.every(n=>n===0));});
test('MIDI RGB framing and Programmer Mode use Pro MK3 identifiers',()=>{assert.deepEqual(Protocol.programmer,[240,0,32,41,2,14,14,1,247]);assert.deepEqual(Protocol.rgb([[11,128,-3,4]]),[240,0,32,41,2,14,3,3,11,127,0,4,247]);assert(Protocol.blackout().length<=538);});
const patch=JSON.parse(fs.readFileSync(path.join(root,'patchers/Lunar Lens.maxpat'))).patcher,boxes=Object.fromEntries(patch.boxes.map(x=>[x.box.id,x.box])),lines=patch.lines.map(x=>x.patchline);
function cable(a,ao,b,bi){assert(lines.some(l=>l.source[0]===a&&l.source[1]===ao&&l.destination[0]===b&&l.destination[1]===bi),`${a}:${ao} -> ${b}:${bi}`);}
test('Every generated cable refers to an existing port',()=>{function check(p){let b=Object.fromEntries(p.boxes.map(x=>[x.box.id,x.box]));for(let {patchline:l} of p.lines){assert(b[l.source[0]]&&b[l.destination[0]]);assert(l.source[1]<b[l.source[0]].numoutlets);assert(l.destination[1]<b[l.destination[0]].numinlets);}for(let {box:x} of p.boxes)if(x.patcher)check(x.patcher);}check(patch);});
test('Feature analysis reads dry selected stereo source before effects / master',()=>{for(let c=0;c<2;c++){cable('file'+c,0,'analysis',c);cable('live'+c,0,'analysis',c);cable('fx',c,'vst',c);}assert(!lines.some(l=>l.destination[0]==='analysis'&&!/^file|^live/.test(l.source[0])));});
test('Snapshots form one coherent 24-value frame, cold inlets first',()=>{for(let i=0;i<24;i++){cable('analysis',i,'snap'+i,0);cable('trig',i,'snap'+i,0);cable('snap'+i,0,'pack',i);}cable('pack',0,'featuretag',0);cable('featuretag',0,'controller',0);});
test('DSP descriptors reach all 24 top-level outlets from the actual Gen codebox',()=>{
 const gen=JSON.parse(fs.readFileSync(path.join(root,'patchers/lens_analysis.gendsp'))).patcher;
 const code=gen.boxes.find(x=>x.box.id==='code').box;
 assert.equal(code.numoutlets,24);assert.equal(boxes.analysis.numoutlets,24);
 for(let i=0;i<24;i++)assert(gen.lines.some(x=>x.patchline.source[0]==='code'&&x.patchline.source[1]===i&&x.patchline.destination[0]==='out'+i));
});
test('Monitor, master, output guard and recorder are physically connected',()=>{for(let c=0;c<2;c++){cable('master',0,'mg'+c,1);cable('mg'+c,0,'guard'+c,0);cable('guard'+c,0,'recorder',c);cable('monitor',0,'mon'+c,1);cable('mon'+c,0,'dac',c);}});
test('Actual UI file selection, MIDI input and LED output reach controller',()=>{cable('drop',0,'loadtag',0);cable('file-dialog',0,'loadtag',0);cable('loadtag',0,'controller',0);cable('midi-in',0,'midi-tag',0);cable('midi-tag',0,'controller',0);cable('controller',1,'lp-out',0);});
test('Production project has no network receiver, score or song cue engine',()=>{assert(!patch.boxes.some(({box:b})=>/udpreceive|node\.script|poly~|transport|seq /.test(b.text||'')));const files=fs.readdirSync(path.join(root,'code'));assert(!files.some(f=>/score|narrative|cue|melody/.test(f)));const proj=JSON.parse(fs.readFileSync(path.join(root,'lunar-lens.maxproj')));assert.equal(proj.autoorganize,0);assert.equal(proj.contents.patchers['Lunar Lens.maxpat'].toplevel,1);});
function runtime(){const calls=[],output=[],objects={};let time=100000;function Task(fn,ctx){this.fn=fn.bind(ctx);this.repeat=()=>{};this.schedule=()=>{};this.cancel=()=>{};}
 const context={Task,post:()=>{},arrayfromargs:x=>Array.from(x),outlet:(...a)=>output.push(a),File:function(){this.isopen=false;},Date:class extends Date{constructor(){super(time);}getTime(){return time;}},patcher:{filepath:root+'/patchers/Lunar Lens.maxpat',getnamed:n=>objects[n]||(objects[n]={message:(...a)=>calls.push([n,...a])})}};
 vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'patchers/lens_runtime.js'),'utf8'),context);return {c:context,calls,output,advance:n=>{time+=n;}};
}
test('Bundled Max controller dispatches UI methods without dynamic includes',()=>{let {c}=runtime();for(let name of ['init','demo','loadfile','play','pause','stop','seek','pad','padup','pressure','features','connect','disconnect','midibyte','blackout','plugininfo','notifydeleted'])assert.equal(typeof c[name],'function',name);assert(!fs.readFileSync(path.join(root,'patchers/lens_runtime.js'),'utf8').includes('include("'));});
test('MIDI running status, zero-velocity releases and real-time bytes interleave correctly',()=>{let {c}=runtime();c.hw=true;c.connected=true;[144,44,100,248,55,90].forEach(c.midibyte);assert.equal(c.visual.gesture().count,2);[160,44,120].forEach(c.midibyte);assert(c.visual.held[44].p>.9);[144,44,0,55,0].forEach(c.midibyte);assert.equal(c.visual.gesture().count,0);});
test('Hardware notes cannot change the scene before connecting Programmer Mode',()=>{let {c}=runtime();[144,44,100,176,95,127].forEach(c.midibyte);assert.equal(c.visual.gesture().count,0);assert.equal(c.P.freeze,false);});
test('Stereo width changes the orbit geometry',()=>{let a=new Visual.Engine(),b=new Visual.Engine();let aa,bb;for(let i=0;i<100;i++){aa=a.step({...f(),width:0},.05,{...params,scene:1});bb=b.step({...f(),width:1},.05,{...params,scene:1});}assert.notDeepEqual(aa,bb);});
test('Connection requires identity AND Programmer layout reply',()=>{let {c}=runtime();c.port('input','LPProMK3 MIDI');c.port('output','LPProMK3 MIDI');c.connect();assert.equal(c.connected,false);[240,126,0,6,2,0,32,41,35,1,0,0,0,4,8,3,247].forEach(c.midibyte);assert.equal(c.connected,false);[240,0,32,41,2,14,0,17,0,0,247].forEach(c.midibyte);assert.equal(c.connected,true);c.disconnect();assert.equal(c.connected,false);});
test('Changing input and stopping release touch effects and prevent live monitoring feedback',()=>{let {c,calls}=runtime();c.pad(44,120);c.param('fx',1);c.param('monitor',1);c.param('input',1);assert.equal(c.P.monitor,false);assert.equal(c.visual.gesture().count,0);assert.equal(c.running,false);assert(calls.some(a=>a[0]==='fx'&&a[1]==='amount'&&a[2]===0));});
test('Unloaded or synth-only plugin cannot replace the dry audio bus',()=>{let {c}=runtime();c.param('plugin',1);assert.equal(c.P.plugin,false);c.plugininfo(-1,2);c.plugininfo(-2,2);c.plugininfo(-7,1);assert.equal(c.pluginReady,false);c.plugininfo(-7,0);assert.equal(c.pluginReady,true);c.param('plugin',1);assert.equal(c.P.plugin,true);});
test('MIDI enumeration cannot replace the MK3 default with the first unrelated port',()=>{let {c}=runtime();c.refreshports();c.port('input','to Max 1');c.portseen('input','append','to Max 1');c.portseen('input','append','Launchpad Pro MK3 LPProMK3 MIDI');c.portseen('output','append','AU DLS Synth 1');c.portseen('output','append','Launchpad Pro MK3 LPProMK3 MIDI');c.applyroutes();assert.equal(c.inputPort,'Launchpad Pro MK3 LPProMK3 MIDI');assert.equal(c.outputPort,'Launchpad Pro MK3 LPProMK3 MIDI');});
test('EOF holds the finished position; Stop returns to zero',()=>{let {c}=runtime();c.duration=48;c.position=47.95;c.loaded=true;c.running=true;c.fileended();c.fileposition(0);assert.equal(c.position,48);assert.equal(c.running,false);c.stop();assert.equal(c.position,0);});
test('Recording requests DSP before opening a file header or starting capture',()=>{let {c,calls}=runtime();c.recordfile('/tmp/lens-test.wav');assert.deepEqual(calls,[['dsp','start']]);c.recordOpenTask.fn();c.recordTask.fn();assert.deepEqual(calls.slice(-2),[['recorder','open','/tmp/lens-test.wav'],['recorder','int',1]]);});
test('Both physical bottom rows select the same roles and flash their feedback LEDs',()=>{let {c,output,advance}=runtime();c.cc(103,127);assert.equal(c.P.focus,2);c.cc(3,0);assert.equal(c.P.focus,2);c.cc(3,127);assert.equal(c.P.focus,0);c.cc(107,127);assert(Math.abs(c.P.bassWeight-1.6)<1e-6);assert.equal(c.buttonUntil[7],c.buttonUntil[107]);c.sendFrame(Array(192).fill(0));let a=output.at(-1)[1];function rgb(n){for(let i=7;i<a.length-1;i+=5)if(a[i+1]===n)return a.slice(i+2,i+5);}assert.deepEqual(Array.from(rgb(107)),[8,32,38]);advance(200);c.sendFrame(Array(192).fill(0));a=output.at(-1)[1];assert.deepEqual(Array.from(rgb(107)),[1,3,5]);});
test('Restore keeps transport and routes while releasing held gestures and visual overrides',()=>{let {c}=runtime();c.loaded=true;c.running=true;c.position=19;c.inputPort='test input';c.P.master=.33;c.pad(44,100);c.P.scene=3;c.P.focus=2;c.P.black=true;c.P.freeze=true;c.defaults();assert.equal(c.running,true);assert.equal(c.position,19);assert.equal(c.inputPort,'test input');assert.equal(c.P.master,.33);assert.equal(c.P.scene,0);assert.equal(c.P.focus,0);assert.equal(c.P.black,false);assert.equal(c.P.freeze,false);assert.equal(c.visual.gesture().count,0);});
test('A deferred halt cannot finish a restarted file, and Restart seeks without another halt',()=>{let {c,calls}=runtime();c.duration=48;c.loaded=true;c.running=true;c.position=13;c.restart();assert.equal(c.position,0);assert(c.running);assert(calls.some(a=>a[0]==='player'&&a[1]==='seek'&&a[2]===0));assert(!calls.some(a=>a[0]==='player'&&a[1]==='int'&&a[2]===0));c.fileended();assert(c.running);assert.equal(c.position,0);c.stop();c.play();c.fileended();assert(c.running);});
test('A low onset sends a visible frame from the feature callback without waiting for the animation timer',()=>{
 const {c,output,advance}=runtime();c.running=true;c.P.focus=1;
 const spec=[0,.12,0,0,0,0,0,0],native=Array(9).fill(0);
 for(let i=0;i<30;i++){advance(20);c.features(...spec,.15,.2,.15,0,.12,.12,.18,...native);}
 const before=output.length;native[8]=.8;advance(20);c.features(...spec,.15,.2,.15,0,.18,.12,.20,...native);
 assert(output.length>before);const state=JSON.parse(output.at(-1)[2]);
 assert.equal(state.features.counts[0],1);assert(state.leds.some(x=>x>3));
});
console.log(`PASS ${count} groups`);
