// Eight overlapping fourth-order constant-peak-gain band-pass measurements.
export const bands = [[30,70],[70,140],[140,280],[280,600],[600,1500],[1500,3500],[3500,7500],[7500,16000]];
export function analysisSource(){
 const a=['// GENERATED by scripts/analysis-source.mjs. Stereo power, before FX / master.',
  'History totalEnergy(0); History monoEnergy(0); History sideEnergy(0); History pk(0);',
  'Param impactLo(35); Param impactHi(160); History impE(0); History impSlow(0); History impPeak(0);',
  'History impLow(35); History impHigh(160);'];
 for(let i=0;i<9;i++)a.push(`History onsetLog${i}(0); History onsetSlope${i}(0); History onsetHold${i}(0); History onsetTimer${i}(0);`);
 for(const c of ['L','R'])for(let s=0;s<2;s++)a.push(`History zi${c}${s}a(0); History zi${c}${s}b(0);`);
 for(let i=0;i<8;i++){
  a.push(`History e${i}(0);`);
  for(const c of ['L','R'])for(let s=0;s<2;s++)a.push(`History z${i}${c}${s}a(0); History z${i}${c}${s}b(0);`);
 }
 a.push('L=dcblock(in1); R=dcblock(in2); ec=1-exp(-1/(samplerate*0.008));');
 a.push('impLow=impLow+(clamp(impactLo,20,160)-impLow)*(1-exp(-1/(samplerate*0.10)));',
  'impHigh=impHigh+(clamp(impactHi,70,400)-impHigh)*(1-exp(-1/(samplerate*0.10)));',
  'fc=sqrt(impLow*max(impLow+25,impHigh)); iq=fc/max(25,impHigh-impLow); iw=twopi*fc/samplerate;',
  'ia=sin(iw)/(2*iq); ib=ia/(1+ia); ia1=-2*cos(iw)/(1+ia); ia2=(1-ia)/(1+ia);');
 for(const c of ['L','R'])for(let s=0;s<2;s++){
  const v=s?`vi${c}0`:c,z=`zi${c}${s}`,out=`vi${c}${s}`;
  a.push(`${out}=ib*${v}+${z}a; ${z}a=-ia1*${out}+${z}b; ${z}b=-ib*${v}-ia2*${out};`);
 }
 // Low-impact timing uses the original 8 ms envelope. Slow body / eight-band motion stay independent.
 a.push('ip=(viL1*viL1+viR1*viR1)*0.5; impEC=1-exp(-1/(samplerate*0.008)); impE=impE+impEC*(ip-impE);',
  'impSlow=impSlow+(1-exp(-1/(samplerate*0.09)))*(ip-impSlow);',
  'impPeak=max(max(abs(viL1),abs(viR1)),impPeak*exp(-1/(samplerate*0.025)));',
  'out13=sqrt(max(0,impE)); out14=sqrt(max(0,impSlow)); out15=impPeak;');
 for(let i=0;i<8;i++){
  const [lo,hi]=bands[i],fc=Math.sqrt(lo*hi),q=fc/(hi-lo);
  a.push(`w${i}=twopi*min(${fc},samplerate*0.44)/samplerate; al${i}=sin(w${i})/(2*${q});`,
   `b${i}=al${i}/(1+al${i}); a${i}1=-2*cos(w${i})/(1+al${i}); a${i}2=(1-al${i})/(1+al${i});`);
  for(const c of ['L','R'])for(let s=0;s<2;s++){
   const v=s?`v${i}${c}0`:c,z=`z${i}${c}${s}`,out=`v${i}${c}${s}`;
   a.push(`${out}=b${i}*${v}+${z}a; ${z}a=-a${i}1*${out}+${z}b; ${z}b=-b${i}*${v}-a${i}2*${out};`);
  }
  a.push(`p${i}=(v${i}L1*v${i}L1+v${i}R1*v${i}R1)*0.5; e${i}=e${i}+(1-exp(-1/(samplerate*${Math.max(.008,Math.min(.04,1.5/fc))})))*(p${i}-e${i}); out${i+1}=sqrt(max(0,e${i}));`);
 }
 // Onset speed is measured in DSP time. GUI polling cannot alter its magnitude.
 for(let i=0;i<9;i++){
  const energy=i===8?'impE':`e${i}`,compression=i===8?100:60,tc=i===8?.008:Math.max(.006,Math.min(.04,1.5/Math.sqrt(bands[i][0]*bands[i][1])));
  a.push(`ol${i}=log(1+sqrt(max(0,${energy}))*${compression}); od${i}=(ol${i}-onsetLog${i})*samplerate*0.02; onsetLog${i}=ol${i};`,
   `onsetSlope${i}=onsetSlope${i}+(1-exp(-1/(samplerate*${tc})))*(od${i}-onsetSlope${i});`,
   `if(onsetSlope${i}>onsetHold${i}) { onsetHold${i}=onsetSlope${i}; onsetTimer${i}=samplerate*0.045; }
   else { onsetTimer${i}=max(0,onsetTimer${i}-1); if(onsetTimer${i}<=0) { onsetHold${i}=onsetHold${i}*exp(-1/(samplerate*0.018)); } }
   out${16+i}=onsetHold${i};`);
 }
 a.push('totalEnergy=totalEnergy+ec*((L*L+R*R)*0.5-totalEnergy);',
  'monoEnergy=monoEnergy+ec*(pow((L+R)*0.5,2)-monoEnergy); sideEnergy=sideEnergy+ec*(pow((L-R)*0.5,2)-sideEnergy);',
  'pk=max(max(abs(L),abs(R)),pk*exp(-1/(samplerate*0.10)));',
  'out9=sqrt(max(0,totalEnergy)); out10=pk; out11=sqrt(max(0,monoEnergy)); out12=sqrt(max(0,sideEnergy));');
 return a.join('\n')+'\n';
}
